#!/bin/bash

# Author:   Nathan Schwarz
# Mail:     nathan.notwhite@gmail.com
# Github:   github.com/nathschwarz
# Jabber:   nath_schwarz@jabber.de

#Get options
while getopts t:p: opt
do
   case $opt in
       t) templatename=$OPTARG;;
       p) profilename=$OPTARG;;
   esac
done
shift $((OPTIND-1))

#Initiate default values for variables
filename=$(echo "$1" | cut -d . -f 1)
FILENAME=$filename
fileextension=$(echo "$1" | cut -d . -f 2)
if [[ -z $templatename ]]; then
    templatename="template"
fi
if [[ -z $profilename ]]; then
    profilename="default"
fi

#Source profile-information
source "$profilename".profile
profilepresets=$(cut -s -d= -f1 "$profilename".profile)

cp ~/prog/pacogen/templates/"$templatename"."$fileextension" $1
for profilepreset in $profilepresets; do
    sed -e "s/$profilepreset/$(eval echo \$$profilepreset)/g" -i "$1" 
done
