#!/bin/bash

# Author:   Nathan Schwarz
# Mail:     nathan.notwhite@gmail.com
# Github:   github.com/nathschwarz
# Jabber:   nath_schwarz@jabber.de

#Initialize templatefuncs-dictionary
declare -A templatefuncs
#Get options
while getopts t:p:f:h opt
do
   case $opt in
        t) templatename=$OPTARG;;
        p) profilename=$OPTARG;;
        f) templatefuncs[${OPTARG%:*}]=${OPTARG##*:};; 
        h) printhelp=true;;
        *) printf "Unkown parameter.\n"; printhelp=true;;
   esac
done
shift $((OPTIND-1))

#Print help, then exit
if [[ -n "$printhelp" ]]; then
    printf "PaCoGen - passive code generator\n"
    printf "\t-t\tName of the template to use\n"
    printf "\t-p\tName of the profile to use\n"
    printf "\t-f\tInclude a function: \$function:\$name\n"
    printf "\t-h\tPrint this help\n"
#    printf "\t-\t\n"
    exit
fi

#Initiate default values for variables
filename=${1%.*}
fileextension=${1##*.}
if [[ -z "$templatename" ]]; then
    templatename="template"
fi
if [[ -z "$profilename" ]]; then
    profilename="default"
fi
if [[ -z "$PACOGEN_PROFILES" ]]; then
    PACOGEN_PROFILES="~/pacogen"
fi
if [[ -z "$PACOGEN_TEMPLATES" ]]; then
    PACOGEN_TEMPLATES="~/pacogen/templates"
fi

#Source profile-information
profilefile="$PACOGEN_PROFILES"/"$profilename".profile 
if [[ ! -e "$profilefile" ]]; then
    printf "Profile file %s in %s not found, exiting.\n" "$profilename" "$PACOGEN_PROFILES"
    exit
else
    source "$profilefile"
    profilepresets=$(cut -s -d= -f1 "$profilefile")
fi

#Copy template file to target and replace placeholders with info
templatefile="$PACOGEN_TEMPLATES"/"$templatename"."$fileextension"
if [[ ! -e "$templatefile" ]]; then
    printf "Template file %s in %s not found, exiting.\n" "$templatename" "$PACOGEN_TEMPLATES"
    exit
else
    #Check if target file is present - if so prompt for overwrite
    if [[ -f "$1" ]]; then
        printf "File %s already exists - overwrite?\n" "$1"
        read answer
        #If prompt-result is 'y' overwrite and proceed - exit otherwise
        if [[ "$answer" = "y" ]]; then
            printf "Overwrite file %s, proceeding.\n" "$1"
        else
            printf "Not overwriting %s, exiting.\n" "$1"
            exit
        fi
    fi

    cp "$templatefile" "$1"
    #Check for 'FILENAME' in template-file 
    sed -e "s/FILENAME/$filename/g" -i "$1"

    #If function-flag is set, replace FUNCTION-placeholder with functions
    if [[ -n "${templatefuncs[@]}" ]]; then
        for func in "${!templatefuncs[@]}"; do
            #cat from function-file and replace placeholder
            cat "$PACOGEN_TEMPLATES/$func.function.$fileextension" >> "$1"
            sed -e "s/FUNCTIONNAME/"${templatefuncs["$func"]}"/g" -i "$1"
        done
    fi

    #Add ending of templatefile, needed for templates for e.g. java
    if [[ -f "$templatefile".end ]]; then
        cat "$templatefile".end >> "$1"
    fi

    #Replace values from profile
    for profilepreset in $profilepresets; do
        sed -e "s/$profilepreset/$(eval echo \$$profilepreset)/g" -i "$1" 
    done
fi
