LICENSE="Proprietary Stuff"
AUTHORSHIP="##AUTHORNAME## (##AUTHORMAIL##)"
AUTHORNAME="Some Name"
AUTHORMAIL="some.name@companyname.com"
PREPDOC="Prepared/preconfigured documentation and gossipping about bullshit the manager said"
